/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as ApiRpcSplatRouteImport } from "./routes/api/rpc/$";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as InventoryRouteImport } from "./routes/inventory";
import { Route as InventoryCategoriesRouteImport } from "./routes/inventory/categories";
import { Route as InventoryIndexRouteImport } from "./routes/inventory/index";
import { Route as InventoryLocationsRouteImport } from "./routes/inventory/locations";
import { Route as InventoryProductsRouteImport } from "./routes/inventory/products";
import { Route as InventoryPurchaseOrdersRouteImport } from "./routes/inventory/purchase-orders";
import { Route as InventoryStockMovementsRouteImport } from "./routes/inventory/stock-movements";
import { Route as InventorySuppliersRouteImport } from "./routes/inventory/suppliers";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as PosRouteImport } from "./routes/pos";
import { Route as PosCustomersRouteImport } from "./routes/pos/customers";
import { Route as PosGiftCardsRouteImport } from "./routes/pos/gift-cards";
import { Route as PosIndexRouteImport } from "./routes/pos/index";
import { Route as PosReturnsRouteImport } from "./routes/pos/returns";
import { Route as PosSalesRouteImport } from "./routes/pos/sales";
import { Route as TodosRouteImport } from "./routes/todos";

const TodosRoute = TodosRouteImport.update({
  id: "/todos",
  path: "/todos",
  getParentRoute: () => rootRouteImport,
} as any);
const PosRoute = PosRouteImport.update({
  id: "/pos",
  path: "/pos",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const InventoryRoute = InventoryRouteImport.update({
  id: "/inventory",
  path: "/inventory",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const PosIndexRoute = PosIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PosRoute,
} as any);
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => InventoryRoute,
} as any);
const PosSalesRoute = PosSalesRouteImport.update({
  id: "/sales",
  path: "/sales",
  getParentRoute: () => PosRoute,
} as any);
const PosReturnsRoute = PosReturnsRouteImport.update({
  id: "/returns",
  path: "/returns",
  getParentRoute: () => PosRoute,
} as any);
const PosGiftCardsRoute = PosGiftCardsRouteImport.update({
  id: "/gift-cards",
  path: "/gift-cards",
  getParentRoute: () => PosRoute,
} as any);
const PosCustomersRoute = PosCustomersRouteImport.update({
  id: "/customers",
  path: "/customers",
  getParentRoute: () => PosRoute,
} as any);
const InventorySuppliersRoute = InventorySuppliersRouteImport.update({
  id: "/suppliers",
  path: "/suppliers",
  getParentRoute: () => InventoryRoute,
} as any);
const InventoryStockMovementsRoute = InventoryStockMovementsRouteImport.update({
  id: "/stock-movements",
  path: "/stock-movements",
  getParentRoute: () => InventoryRoute,
} as any);
const InventoryPurchaseOrdersRoute = InventoryPurchaseOrdersRouteImport.update({
  id: "/purchase-orders",
  path: "/purchase-orders",
  getParentRoute: () => InventoryRoute,
} as any);
const InventoryProductsRoute = InventoryProductsRouteImport.update({
  id: "/products",
  path: "/products",
  getParentRoute: () => InventoryRoute,
} as any);
const InventoryLocationsRoute = InventoryLocationsRouteImport.update({
  id: "/locations",
  path: "/locations",
  getParentRoute: () => InventoryRoute,
} as any);
const InventoryCategoriesRoute = InventoryCategoriesRouteImport.update({
  id: "/categories",
  path: "/categories",
  getParentRoute: () => InventoryRoute,
} as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: "/api/rpc/$",
  path: "/api/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/inventory": typeof InventoryRouteWithChildren;
  "/login": typeof LoginRoute;
  "/pos": typeof PosRouteWithChildren;
  "/todos": typeof TodosRoute;
  "/inventory/categories": typeof InventoryCategoriesRoute;
  "/inventory/locations": typeof InventoryLocationsRoute;
  "/inventory/products": typeof InventoryProductsRoute;
  "/inventory/purchase-orders": typeof InventoryPurchaseOrdersRoute;
  "/inventory/stock-movements": typeof InventoryStockMovementsRoute;
  "/inventory/suppliers": typeof InventorySuppliersRoute;
  "/pos/customers": typeof PosCustomersRoute;
  "/pos/gift-cards": typeof PosGiftCardsRoute;
  "/pos/returns": typeof PosReturnsRoute;
  "/pos/sales": typeof PosSalesRoute;
  "/inventory/": typeof InventoryIndexRoute;
  "/pos/": typeof PosIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/todos": typeof TodosRoute;
  "/inventory/categories": typeof InventoryCategoriesRoute;
  "/inventory/locations": typeof InventoryLocationsRoute;
  "/inventory/products": typeof InventoryProductsRoute;
  "/inventory/purchase-orders": typeof InventoryPurchaseOrdersRoute;
  "/inventory/stock-movements": typeof InventoryStockMovementsRoute;
  "/inventory/suppliers": typeof InventorySuppliersRoute;
  "/pos/customers": typeof PosCustomersRoute;
  "/pos/gift-cards": typeof PosGiftCardsRoute;
  "/pos/returns": typeof PosReturnsRoute;
  "/pos/sales": typeof PosSalesRoute;
  "/inventory": typeof InventoryIndexRoute;
  "/pos": typeof PosIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/inventory": typeof InventoryRouteWithChildren;
  "/login": typeof LoginRoute;
  "/pos": typeof PosRouteWithChildren;
  "/todos": typeof TodosRoute;
  "/inventory/categories": typeof InventoryCategoriesRoute;
  "/inventory/locations": typeof InventoryLocationsRoute;
  "/inventory/products": typeof InventoryProductsRoute;
  "/inventory/purchase-orders": typeof InventoryPurchaseOrdersRoute;
  "/inventory/stock-movements": typeof InventoryStockMovementsRoute;
  "/inventory/suppliers": typeof InventorySuppliersRoute;
  "/pos/customers": typeof PosCustomersRoute;
  "/pos/gift-cards": typeof PosGiftCardsRoute;
  "/pos/returns": typeof PosReturnsRoute;
  "/pos/sales": typeof PosSalesRoute;
  "/inventory/": typeof InventoryIndexRoute;
  "/pos/": typeof PosIndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/inventory"
    | "/login"
    | "/pos"
    | "/todos"
    | "/inventory/categories"
    | "/inventory/locations"
    | "/inventory/products"
    | "/inventory/purchase-orders"
    | "/inventory/stock-movements"
    | "/inventory/suppliers"
    | "/pos/customers"
    | "/pos/gift-cards"
    | "/pos/returns"
    | "/pos/sales"
    | "/inventory/"
    | "/pos/"
    | "/api/auth/$"
    | "/api/rpc/$";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/dashboard"
    | "/login"
    | "/todos"
    | "/inventory/categories"
    | "/inventory/locations"
    | "/inventory/products"
    | "/inventory/purchase-orders"
    | "/inventory/stock-movements"
    | "/inventory/suppliers"
    | "/pos/customers"
    | "/pos/gift-cards"
    | "/pos/returns"
    | "/pos/sales"
    | "/inventory"
    | "/pos"
    | "/api/auth/$"
    | "/api/rpc/$";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/inventory"
    | "/login"
    | "/pos"
    | "/todos"
    | "/inventory/categories"
    | "/inventory/locations"
    | "/inventory/products"
    | "/inventory/purchase-orders"
    | "/inventory/stock-movements"
    | "/inventory/suppliers"
    | "/pos/customers"
    | "/pos/gift-cards"
    | "/pos/returns"
    | "/pos/sales"
    | "/inventory/"
    | "/pos/"
    | "/api/auth/$"
    | "/api/rpc/$";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRoute;
  InventoryRoute: typeof InventoryRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  PosRoute: typeof PosRouteWithChildren;
  TodosRoute: typeof TodosRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/todos": {
      id: "/todos";
      path: "/todos";
      fullPath: "/todos";
      preLoaderRoute: typeof TodosRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pos": {
      id: "/pos";
      path: "/pos";
      fullPath: "/pos";
      preLoaderRoute: typeof PosRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/inventory": {
      id: "/inventory";
      path: "/inventory";
      fullPath: "/inventory";
      preLoaderRoute: typeof InventoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pos/": {
      id: "/pos/";
      path: "/";
      fullPath: "/pos/";
      preLoaderRoute: typeof PosIndexRouteImport;
      parentRoute: typeof PosRoute;
    };
    "/inventory/": {
      id: "/inventory/";
      path: "/";
      fullPath: "/inventory/";
      preLoaderRoute: typeof InventoryIndexRouteImport;
      parentRoute: typeof InventoryRoute;
    };
    "/pos/sales": {
      id: "/pos/sales";
      path: "/sales";
      fullPath: "/pos/sales";
      preLoaderRoute: typeof PosSalesRouteImport;
      parentRoute: typeof PosRoute;
    };
    "/pos/returns": {
      id: "/pos/returns";
      path: "/returns";
      fullPath: "/pos/returns";
      preLoaderRoute: typeof PosReturnsRouteImport;
      parentRoute: typeof PosRoute;
    };
    "/pos/gift-cards": {
      id: "/pos/gift-cards";
      path: "/gift-cards";
      fullPath: "/pos/gift-cards";
      preLoaderRoute: typeof PosGiftCardsRouteImport;
      parentRoute: typeof PosRoute;
    };
    "/pos/customers": {
      id: "/pos/customers";
      path: "/customers";
      fullPath: "/pos/customers";
      preLoaderRoute: typeof PosCustomersRouteImport;
      parentRoute: typeof PosRoute;
    };
    "/inventory/suppliers": {
      id: "/inventory/suppliers";
      path: "/suppliers";
      fullPath: "/inventory/suppliers";
      preLoaderRoute: typeof InventorySuppliersRouteImport;
      parentRoute: typeof InventoryRoute;
    };
    "/inventory/stock-movements": {
      id: "/inventory/stock-movements";
      path: "/stock-movements";
      fullPath: "/inventory/stock-movements";
      preLoaderRoute: typeof InventoryStockMovementsRouteImport;
      parentRoute: typeof InventoryRoute;
    };
    "/inventory/purchase-orders": {
      id: "/inventory/purchase-orders";
      path: "/purchase-orders";
      fullPath: "/inventory/purchase-orders";
      preLoaderRoute: typeof InventoryPurchaseOrdersRouteImport;
      parentRoute: typeof InventoryRoute;
    };
    "/inventory/products": {
      id: "/inventory/products";
      path: "/products";
      fullPath: "/inventory/products";
      preLoaderRoute: typeof InventoryProductsRouteImport;
      parentRoute: typeof InventoryRoute;
    };
    "/inventory/locations": {
      id: "/inventory/locations";
      path: "/locations";
      fullPath: "/inventory/locations";
      preLoaderRoute: typeof InventoryLocationsRouteImport;
      parentRoute: typeof InventoryRoute;
    };
    "/inventory/categories": {
      id: "/inventory/categories";
      path: "/categories";
      fullPath: "/inventory/categories";
      preLoaderRoute: typeof InventoryCategoriesRouteImport;
      parentRoute: typeof InventoryRoute;
    };
    "/api/rpc/$": {
      id: "/api/rpc/$";
      path: "/api/rpc/$";
      fullPath: "/api/rpc/$";
      preLoaderRoute: typeof ApiRpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface InventoryRouteChildren {
  InventoryCategoriesRoute: typeof InventoryCategoriesRoute;
  InventoryLocationsRoute: typeof InventoryLocationsRoute;
  InventoryProductsRoute: typeof InventoryProductsRoute;
  InventoryPurchaseOrdersRoute: typeof InventoryPurchaseOrdersRoute;
  InventoryStockMovementsRoute: typeof InventoryStockMovementsRoute;
  InventorySuppliersRoute: typeof InventorySuppliersRoute;
  InventoryIndexRoute: typeof InventoryIndexRoute;
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryCategoriesRoute: InventoryCategoriesRoute,
  InventoryLocationsRoute: InventoryLocationsRoute,
  InventoryProductsRoute: InventoryProductsRoute,
  InventoryPurchaseOrdersRoute: InventoryPurchaseOrdersRoute,
  InventoryStockMovementsRoute: InventoryStockMovementsRoute,
  InventorySuppliersRoute: InventorySuppliersRoute,
  InventoryIndexRoute: InventoryIndexRoute,
};

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren
);

interface PosRouteChildren {
  PosCustomersRoute: typeof PosCustomersRoute;
  PosGiftCardsRoute: typeof PosGiftCardsRoute;
  PosReturnsRoute: typeof PosReturnsRoute;
  PosSalesRoute: typeof PosSalesRoute;
  PosIndexRoute: typeof PosIndexRoute;
}

const PosRouteChildren: PosRouteChildren = {
  PosCustomersRoute: PosCustomersRoute,
  PosGiftCardsRoute: PosGiftCardsRoute,
  PosReturnsRoute: PosReturnsRoute,
  PosSalesRoute: PosSalesRoute,
  PosIndexRoute: PosIndexRoute,
};

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRouteWithChildren,
  LoginRoute: LoginRoute,
  PosRoute: PosRouteWithChildren,
  TodosRoute: TodosRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";

import type { getRouter } from "./router.tsx";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
